### ISSUE TITLE
player.write(data); Need clarification on what data is..

### ISSUE THREAD

**Issue by vigostudio** [stanford-oval/node-pulseaudio#19]
Hi,

In the example, it has been mentioned that there is player.write(data)

When running the example, it says data undefined.

Can you help me regarding what data means in this function.

**Comment by gcampax** [comment]
Hi! The example is pseudo-code, not directly runnable.
`data` in the example is the sound data you want to play (by default, in stereo PCM, 44.1 kHz, 16 bit signed normalized format).

You can look in the "test" folder for some complete examples.

**Comment by gcampax** [comment]
Closing this. Please reopen if you have further questions.
