### ISSUE TITLE
Clarification: Pulse Audio Stream Format? 

### ISSUE THREAD

**Issue by oliverlorenz** [stanford-oval/node-pulseaudio#7]
Hello!

I would like to access a pulseaudio stream using this framework. My final goal is to create an opus stream that I can send to discord. I am aware that this is not part of this framework. But one step at a time. I just wanted to give context.

I have basically managed to access my audio device with the framework. But I only get a strange noise when I pipe the stream into a file.

This is my code that I wrote:

```
import * as fs from 'fs';

const PulseAudio = require('@johnf/pulseaudio2');
const context = new PulseAudio({
    client: "my-awesome-app", 
    server: "my-preferred-server",
});

const stream = context.createRecordStream({
    stream: "my-awesome-stream",
    device: "alsa_input.usb-RODE_MICROPHONESj_Rode_Podcaster-00.analog-mono",
    channels: 2,
});

const fileStream = fs.createWriteStream('./test.wav', { encoding: 'binary' });
stream.pipe(fileStream)
```

The result sounds like this:

[https://filebin.net/w1cdvi5lk2u4vqt8](https://filebin.net/w1cdvi5lk2u4vqt8)

Audacity looks like this:

[https://filebin.net/5ntgebycgfgebsof](https://filebin.net/5ntgebycgfgebsof)

I feel like there's something fundamentally wrong with my understanding. What format comes out of such a stream? My assumption so far was that it is simply WAV. But that doesn't seem to be correct. What is it instead? 

I have the feeling that I need to convert something here, but I'm not sure what exactly the input format is and what output format I need for further processing. 

Can anyone here answer this question?

**Comment by lf94** [comment]
@oliverlorenz I'll be on this similar journey. I'll let you know if I discover anything.

**Comment by lf94** [comment]
Seems to be whatever format you specify (S16LE, 44100 sample rate by default).

**Comment by lf94** [comment]
You're probably having issues playing the file because of the lack of header/container.  See https://en.wikipedia.org/wiki/WAV for more information.

**Comment by gcampax** [comment]
Hi, sorry for the late reply. The format is raw PCM audio, with no header. You can save it to wav if you add the appropriate header. The format is S16LE at 44100 Hz, but you can change both. See the readme for details.

**Comment by Jan8787** [comment]
Lg

**Comment by gcampax** [comment]
Closing this. If you have any further question, feel free to reopen.
